services:
  service.example:
    class: ../controllers/StatusGetController
    arguments: []

  Apps.controllers.BillPutController:
    class: ../controllers/CoursePutController
    arguments: ['@Bills.application.BillCreate']

  Bills.application.BillCreate:
    class: ../../Contexts/Bills/application/BillCreate
    arguments: [""]
